baseURL = "https://mellifluous-paprenjak-d598f2.netlify.app/"
languageCode = "fr-fr"
title = "Neat AI"
theme = "hugo-theme-stack"

[params]
  description = "Un blog dédié à l'intelligence artificielle, ses applications et son impact futur."
  darkMode = true
  shareButtons = true
  logo = "images/logo.png"
  favicon = "images/favicon.ico"

  [params.social]
    twitter = "https://twitter.com/VotreCompte"
    facebook = "https://facebook.com/VotreCompte"
    linkedin = "https://linkedin.com/in/VotreCompte"

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
